'use client'
import { useEffect,useState,useRef,useMemo } from 'react'
import { Droplets,Plus,LocateFixed,Leaf,Waves,Trash2,Fish,Bird,CloudRain,AlertTriangle,RefreshCw,Download,Sparkles } from 'lucide-react'
import { Map as MapIcon,ChartNoAxesCombined,Camera,ShieldCheck,MapPin,X,ArrowUpRight,CheckCircle2 } from 'lucide-react'
import Link from 'next/link'
import { Menu,Info,BookOpen,HelpCircle,ChevronRight,Eye } from 'lucide-react'
import { observationEmojis } from '@/lib/observation-emojis'
const emojiIcon=(id:string)=>function CategoryEmoji(){return <span aria-hidden="true" className="category-emoji">{observationEmojis[id]}</span>}
import { EvidenceLoop } from '@/components/evidence-loop'
import { RealMap } from '@/components/real-map'
const categories=[['hyacinth','Water hyacinth',emojiIcon('hyacinth')],['algae','Algae / scum',emojiIcon('algae')],['grass','Aquatic plants',emojiIcon('grass')],['litter','Litter',emojiIcon('litter')],['fish','Dead fish',emojiIcon('fish')],['wildlife','Aquatic life',emojiIcon('wildlife')],['flooding','Flooding',emojiIcon('flooding')],['unusual','Unusual water',emojiIcon('unusual')]] as const
type Point={latitude:number;longitude:number;name?:string;accuracy?:number;timestamp?:number;water_body_id?:string}
type Report=Point&{id:string;category:string;description:string;photo_url:string;created_at:string;ai_assessment?:any;confirmation_count?:number|null;observed_at?:string;water_body_id?:string;water_body?:any}
export default function Page(){
 const [location,setLocation]=useState<Point|null>(null),[selected,setSelected]=useState<Point|null>(null),[reports,setReports]=useState<Report[]>([]),[notice,setNotice]=useState(''),[view,setView]=useState('explore'),[filter,setFilter]=useState('all'),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[locating,setLocating]=useState(false),[detail,setDetail]=useState<Report|null>(null),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[category,setCategory]=useState('hyacinth'),[description,setDescription]=useState(''),[name,setName]=useState(''),[coverage,setCoverage]=useState('Unknown')
 const [observedAt,setObservedAt]=useState(''),[consent,setConsent]=useState(false),[parentId,setParentId]=useState('')
 useEffect(()=>{const d=new Date();setObservedAt(new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16))},[])
 const menuRef=useRef<HTMLDialogElement>(null)
 const [review,setReview]=useState<{count:number;confirmed:boolean}|null>(null),[reviewLoading,setReviewLoading]=useState(false),[reviewError,setReviewError]=useState(''),[attested,setAttested]=useState(false),[reviewSaving,setReviewSaving]=useState(false),[retrying,setRetrying]=useState(false)
 useEffect(()=>{if(!detail)return;let cancelled=false;setReview(null);setAttested(false);setReviewError('');setReviewLoading(true);fetch('/api/confirmations?id='+detail.id).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(!cancelled)setReview(d)}).catch(e=>{if(!cancelled)setReviewError(e.message)}).finally(()=>{if(!cancelled)setReviewLoading(false)});return()=>{cancelled=true}},[detail?.id])
 async function confirmObservation(){if(!detail||!attested||reviewSaving||review?.confirmed)return;const id=detail.id;setReviewSaving(true);setReviewError('');try{const r=await fetch('/api/confirmations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({observationId:id})});const d=await r.json();if(!r.ok)throw Error(d.error);setReview(d);setReports(rows=>rows.map(row=>row.id===id?{...row,confirmation_count:d.count}:row));setDetail(row=>row?.id===id?{...row,confirmation_count:d.count}:row)}catch(e){setReviewError((e as Error).message)}finally{setReviewSaving(false)}}
 async function retryAssessment(){if(!detail||retrying)return;const id=detail.id;setRetrying(true);setReviewError('');try{const r=await fetch('/api/assess-observation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({observationId:id}),signal:AbortSignal.timeout(90000)});const d=await r.json();if(!r.ok)throw Error('AI request failed');setDetail(row=>row?.id===id?{...row,ai_assessment:d}:row);setReports(rows=>rows.map(row=>row.id===id?{...row,ai_assessment:d}:row));if(d.unavailable)setReviewError('AI provider is still unavailable. The report is saved; community review remains available.')}catch{setReviewError('AI screening could not complete. Your report is still saved.')}finally{setRetrying(false)}}
 const dialogRef=useRef<HTMLDialogElement>(null)
 useEffect(()=>{if(detail){dialogRef.current?.showModal()}else{dialogRef.current?.close()}},[detail])
 const [days,setDays]=useState(0),[ownIds,setOwnIds]=useState<string[]>([]),[tipVisible,setTipVisible]=useState(true)
 useEffect(()=>{try{setOwnIds((()=>{const ids=JSON.parse(localStorage.getItem('limnora-contributions')||'[]');return Array.isArray(ids)?ids.filter((id:unknown)=>typeof id==='string'):[]})())}catch{}},[])
 useEffect(()=>{if(view==='report')document.getElementById('report-form')?.scrollIntoView({behavior:'smooth',block:'start'});if(view==='insights')document.getElementById('community-insights')?.scrollIntoView({behavior:'smooth',block:'start'})},[view])
 async function refresh(){setLoading(true);try{const r=await fetch('/api/observations');const d=await r.json();if(!r.ok)throw Error(d.error);setReports(d.observations)}catch(e){setNotice((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{refresh()},[])
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview])
 function locate(){if(!navigator.geolocation){setNotice('Location unavailable');return}setLocating(true);navigator.geolocation.getCurrentPosition(p=>{setLocation({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,timestamp:p.timestamp});setLocating(false);setNotice('Location found. Click a nearby pond or lake.')},e=>{setLocating(false);setNotice(e.code===1?'Allow Location in browser site settings.':'Location unavailable or timed out. Enable device location and retry.')},{enableHighAccuracy:true,timeout:20000,maximumAge:0})}
 function select(p:Point){setParentId('');setSelected(p);setName(p.name||'');setView('report');setNotice('Water point selected. Check its name and add a photo.')}
 async function submit(e:React.FormEvent){e.preventDefault();if(saving)return;if(!selected){setNotice('Select a water body on the map first.');return}if(!observedAt||!consent){setNotice('Set the observation date and confirm public photo / AI processing consent.');return}if(!file){setNotice('Choose a JPEG, PNG or WebP photo under 5 MB before submitting.');return}setSaving(true);setNotice('Uploading photo and saving your observation…');try{const f=new FormData();f.set('photo',file);f.set('latitude',String(selected.latitude));f.set('longitude',String(selected.longitude));f.set('category',category);f.set('description',description);f.set('name',name);f.set('coverage',coverage);f.set('observedAt',observedAt?new Date(observedAt).toISOString():'');f.set('consent',String(consent));if(selected.water_body_id)f.set('waterBodyId',selected.water_body_id);if(parentId)f.set('parentId',parentId);const r=await fetch('/api/observations',{method:'POST',body:f,signal:AbortSignal.timeout(45000)});const d=await r.json();if(!r.ok)throw Error(d.error);setDetail(d.observation);setOwnIds(previous=>{const ids=[...previous,d.observation.id];try{localStorage.setItem('limnora-contributions',JSON.stringify(ids))}catch{}return ids});setFile(null);setPreview('');setNotice('Report saved. Checking photo evidence…');await refresh();const ai=await fetch('/api/assess-observation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({observationId:d.observation.id}),signal:AbortSignal.timeout(90000)});if(!ai.ok)throw Error('Report saved, but AI assessment failed. Do not resubmit the report.');const assessment=await ai.json();setDetail({...d.observation,ai_assessment:assessment});setNotice(assessment.unavailable?'Report saved; AI unavailable. Human review recommended.':'Report saved and evidence assessed. Human review recommended.');setFile(null);setPreview('');setDescription('');setParentId('');setConsent(false);setView('explore');await refresh()}catch(e){setNotice((e as Error).message)}finally{setSaving(false)}}
 function exportData(){if(!detail)return;const u=URL.createObjectURL(new Blob([JSON.stringify(detail,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='limnora-observation.json';a.click();URL.revokeObjectURL(u)}
 const visible=useMemo(()=>reports.filter(r=>(filter==='all'||r.category===filter)&&(!days||Date.now()-new Date(r.created_at).getTime()<=days*86400000)),[reports,filter,days])
 const nearby=location?visible.filter(r=>Math.hypot((r.latitude-location.latitude)*111,(r.longitude-location.longitude)*111*Math.cos(location.latitude*Math.PI/180))<=5):[]
 const categoryLabel=(id:string)=>categories.find(c=>c[0]===id)?.[1]||id
 return <main>
 <a href="#report-form" className="skip-link">Skip to report form</a>
 <header className="app-header"><div className="header-inner">
 <button className="brand" onClick={()=>{setView('explore');window.scrollTo({top:0,behavior:'smooth'})}}><span className="brand-mark"><img src="/limnora-mark.svg" alt="" width={56} height={56}/></span><span>Limnora<small>Freshwater. Evidence. Community.</small></span></button>
 <nav aria-label="Main navigation">{[['explore',MapIcon],['report',Plus],['insights',ChartNoAxesCombined]].map(([v,Icon])=><button className={view===v?'active':''} onClick={()=>{setView(v as string);if(v==='explore')window.scrollTo({top:0,behavior:'smooth'});else document.getElementById(v==='report'?'report-form':'community-insights')?.scrollIntoView({behavior:'smooth',block:'start'})}} key={v as string}><Icon/>{v as string}</button>)}</nav>
 <div className="header-count"><strong>{reports.length}</strong><small>community reports</small></div><button className="menu-button" aria-label="Open navigation menu" onClick={()=>menuRef.current?.showModal()}><Menu/></button>
 </div></header>
 <div className="workspace">
 {tipVisible&&<section className="field-note"><Leaf/><div><strong>Small observations. A clearer picture of our water.</strong><p>Notice floating plants, algae or litter? Record what you can see from a safe public bank. A photo is evidence—not a water-quality test.</p></div><button aria-label="Dismiss field note" onClick={()=>setTipVisible(false)}><X/></button></section>}
 <section className="explore-grid">
 <div className="map-column"><div className="map-card">
 <div className="toolbar"><div><MapIcon/><strong>Explore freshwater</strong></div><span>{visible.length} observations</span></div>
 <div className="map-filters"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>All</button>{categories.map(([id,label,Icon])=><button key={id} title={label} aria-label={'Filter '+label} aria-pressed={filter===id} className={filter===id?'active':''} onClick={()=>setFilter(filter===id?'all':id)}><Icon/><span>{label}</span></button>)}</div>
 <RealMap location={location} onLocate={locate} onSelect={select} reports={visible} onReportClick={p=>{const r=reports.find(r=>r.id===p.id);if(r)setDetail(r)}} selected={selected}/>
 <div className="map-footer"><MapPin/><span>{location?'Your position is shown in green. Select blue water anywhere.':'Select water anywhere. Your location is optional.'}</span><button onClick={locate} disabled={locating}><LocateFixed/>{locating?'Finding…':location?'Recenter':'Locate me'}</button></div>
 </div>
 <section className="panel insights-panel" id="community-insights"><div className="section-heading"><div><p className="eyebrow">COMMUNITY PICTURE</p><h2>What’s being observed</h2></div><ChartNoAxesCombined/></div><p>Counts from up to 200 recent submitted observations, not measured ecosystem health. The category chart uses original observer labels, not automatically corrected AI labels.</p><p className="small">{reports.filter(r=>r.ai_assessment?.status==='completed'&&!r.ai_assessment.observation_supported).length} AI / observer disagreements · {reports.reduce((n,r)=>n+(r.ai_assessment?.review_history?.length||0),0)} human reviews. These are evidence-quality signals, not pollution predictions.</p>
 <div className="insight-counts"><div><strong>{visible.length}</strong><small>in this time period</small></div><div><strong>{visible.filter(r=>r.ai_assessment&&!r.ai_assessment.unavailable&&r.ai_assessment.predicted_category).length}</strong><small>AI screenings available</small></div><div><strong>{location?nearby.length:'—'}</strong><small>within 5 km of you</small></div></div>
 {categories.map(([id,label,Icon])=>{const count=visible.filter(r=>r.category===id).length;return <button className="insight-row" key={id} onClick={()=>setFilter(filter===id?'all':id)}><Icon/><span>{label}</span><div className="bar-track"><div style={{width:visible.length?count/visible.length*100+'%':'0%'}}/></div><strong>{count}</strong></button>})}
 <div className="safety"><ShieldCheck/>AI supports human judgment. These reports cannot establish whether water is safe for drinking, bathing or animals.</div></section>
 </div>
 <aside className="sidebar">
 <section className="panel report" id="report-form"><div className="section-heading"><h1>Report an observation</h1><span className="small-tag">No signup</span></div><p className="form-intro">Help assess a pond, lake or stream from anywhere. Add field evidence; AI explains what is visible for human review.</p>
 <div className="location-card"><MapPin/><div><strong>{selected?name||'Unnamed water body':'Choose a pond, lake or stream'}</strong><small>{selected?selected.latitude.toFixed(4)+', '+selected.longitude.toFixed(4):'Zoom in and tap its blue water surface. No GPS required.'}</small></div>{selected&&<CheckCircle2/>}</div>
 <button className="location-button" onClick={locate} disabled={locating}><LocateFixed/>{locating?'Finding your position…':location?'Refresh my location':'Use my location (optional)'}{location?.accuracy!==undefined&&<small>±{Math.round(location.accuracy)} m</small>}</button>
 <details className="guidelines"><summary><ShieldCheck/>Reporting guidelines</summary><ul><li>Stay on public land. Do not enter or touch suspicious water.</li><li>Use a real photo from your visit; no AI-generated field evidence.</li><li>Your photo and water point are public. Avoid faces and private details.</li><li>Reports use a manually selected water point—not GPS-verified presence.</li></ul></details>
 <form noValidate onSubmit={submit}>
 <p className="field-label">WHAT DID YOU NOTICE?</p><div className="categories">{categories.map(([id,label,Icon])=><button type="button" aria-pressed={category===id} className={category===id?'active':''} key={id} onClick={()=>setCategory(id)}><Icon/><span>{label}</span></button>)}</div>
 <label>Or use an existing water-body record<select value={selected?.water_body_id||''} onChange={e=>{const r=reports.find(r=>r.water_body_id===e.target.value);if(r)select({...r,name:r.water_body?.name||r.description.split(':')[0]})}}><option value="">New map-selected water point</option>{Array.from(new Map(reports.filter(r=>r.water_body_id).map(r=>[r.water_body_id,r])).values()).map(r=><option key={r.water_body_id} value={r.water_body_id}>{r.water_body?.name||r.description.split(':')[0]}</option>)}</select></label>
 {parentId&&<div className="notice">Follow-up linked to the earlier observation. Add a new photo; the original record stays unchanged.<button type="button" onClick={()=>setParentId('')}>Cancel follow-up</button></div>}
 <label>When did you observe this?<input type="datetime-local" required value={observedAt} onChange={e=>setObservedAt(e.target.value)}/><small>Your visit date, not necessarily today.</small></label>
 <label>Water-body name <span className="optional">optional if unnamed</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="Name from map, or local name" maxLength={120}/></label>
 <label className="photo-field"><span><Camera/>Photo evidence <span className="required">required</span></span><input required type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>{const f=e.target.files?.[0];setFile(null);setPreview('');if(!f)return;if(f.size>5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(f.type)){setNotice('Choose a JPEG, PNG or WebP image under 5 MB');e.target.value='';return}setFile(f);setPreview(URL.createObjectURL(f));setNotice('Photo ready. Check your observation and submit.')}}/><small>JPEG, PNG or WebP · up to 5 MB · GPS/EXIF removed on upload</small></label>
 {preview&&<img src={preview} className="preview" alt="Your selected observation photo"/>}
 <label>Visible coverage<select value={coverage} onChange={e=>setCoverage(e.target.value)}>{['Unknown','Less than 25%','25–50%','More than 50%'].map(v=><option key={v}>{v}</option>)}</select></label>
 <label>What did you see? <span className="optional">optional</span><textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={1500} placeholder="For example: floating plants along the north bank, with some open water."/></label>
 <label className="attestation"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I have permission to share this real field photo publicly and send it to an external AI provider. No faces or private details.</label>
 <p className="small consent-copy"><Sparkles/>External AI screens visible evidence and explains uncertainty. It does not confirm species, toxicity or photo authenticity.</p>
 {notice&&<div className="notice" role="status" aria-live="polite">{notice}</div>}
 <button type="submit" className="primary submit-button" disabled={saving}>{saving?<RefreshCw className="spin"/>:<Plus/>}{saving?'Saving and screening…':'Submit observation'}</button>
 </form></section>
 <section className="panel"><div className="time-filters" aria-label="Report time period">{[[0,'All time'],[7,'7 days'],[30,'30 days'],[90,'3 months']].map(([value,label])=><button key={value} aria-pressed={days===value} className={days===value?'active':''} onClick={()=>setDays(value as number)}>{label}</button>)}</div><p className="small">Filtered by submission date. Newest first.</p></section>
 <section className="panel"><div className="section-heading"><h2>Recent observations</h2><button onClick={refresh} aria-label="Refresh reports"><RefreshCw className={loading?'spin':''}/></button></div>{loading?<div className="skeleton-list" aria-label="Loading reports"><div/><div/><div/></div>:visible.length?visible.slice(0,12).map(r=><button key={r.id} className="report-row" onClick={()=>setDetail(r)}><img src={r.photo_url} alt={categoryLabel(r.category)+' observation'}/><span><strong>{categoryLabel(r.category)}</strong><small>{r.description.slice(0,85)}</small><time>{new Date(r.created_at).toLocaleDateString()}</time><small className="corroboration-label">👀 {r.confirmation_count===null?'Confirmations unavailable':(r.confirmation_count||0)+' saw this too'} · {r.ai_assessment?.unavailable?'Human review needed':r.ai_assessment?.predicted_category?'AI screened · not verified':'AI pending'}</small></span><ArrowUpRight/></button>):<div className="empty-state"><Waves/><strong>No observations in this view</strong><p>Try another filter, or start a record for your local water.</p></div>}</section>
 <section className="panel"><h2>This week near you</h2>{location?<><p><strong>{reports.filter(r=>Date.now()-new Date(r.created_at).getTime()<7*86400000&&Math.hypot((r.latitude-location.latitude)*111,(r.longitude-location.longitude)*111*Math.cos(location.latitude*Math.PI/180))<=5).length}</strong> reports within 5 km this week.</p><p className="small">Citizen observations can help identify places needing follow-up. No reports does not mean healthy water.</p></>:<><p>Enable location to see observations within 5 km.</p><button onClick={locate} disabled={locating}><LocateFixed/>Locate me</button></>}</section>
 <section className="panel contributions"><Leaf/><h2>Your contributions</h2><strong>{ownIds.length}</strong><p>{ownIds.length?'Observations submitted from this browser. Thank you for building the record.':'Your first report can help someone notice a change.'}</p><small>Stored on this browser only. No account or leaderboard.</small></section>
 </aside></section>
 <footer><span className="footer-brand"><img src="/limnora-mark.svg" alt="" width={28} height={28}/>Limnora</span><span>Healthy waters. Healthy ecosystems. Healthier communities.</span><a href="#report-form">Report responsibly</a></footer>
 </div>
 <dialog ref={dialogRef} className="detail-dialog" aria-label="Observation detail" onCancel={()=>setDetail(null)} onClick={e=>{if(e.target===e.currentTarget)setDetail(null)}}>{detail&&<section className="panel detail-panel"><div className="section-heading"><div><p className="eyebrow">COMMUNITY EVIDENCE</p><h2><span aria-hidden="true">{observationEmojis[detail.category]}</span> {categoryLabel(detail.category)}</h2></div><button autoFocus aria-label="Close observation" onClick={()=>setDetail(null)} onKeyDown={e=>{if(e.key==='Escape')setDetail(null)}}><X/></button></div><img className="preview" src={detail.photo_url} alt={categoryLabel(detail.category)+' submitted evidence'}/><div className="report-metadata"><strong>{detail.description?.split(':')[0]||'Unnamed water body'}</strong><span className="small-tag">Community report · unverified</span></div><p>{detail.description?.split(':').slice(1).join(':').trim()||'No additional description provided.'}</p><p className="small">Observed {new Date(detail.observed_at||detail.created_at).toLocaleString()} · {detail.latitude.toFixed(4)}, {detail.longitude.toFixed(4)}</p><EvidenceLoop key={detail.id} report={detail} timeline={reports.filter(r=>detail.water_body_id?r.water_body_id===detail.water_body_id:r.id===detail.id||r.ai_assessment?.parent_id===detail.id)} onOpen={setDetail} onChange={updated=>{setDetail(current=>current?.id===updated.id?updated:current);setReports(rows=>rows.map(r=>r.id===updated.id?updated:r))}} onFollowUp={()=>{setSelected({...detail,name:detail.water_body?.name||detail.description.split(':')[0]});setName(detail.water_body?.name||detail.description.split(':')[0]);setParentId(detail.id);setDetail(null);setView('report');setNotice('Add new photo evidence from your visit. Original report is preserved.')}}/><section className="community-review"><h3>👀 Community corroboration</h3><strong>{reviewLoading?'Loading confirmations…':review?(review.count+' community confirmations'):'Confirmation count unavailable'}</strong><p>Only confirm if you personally observed the same condition at this water body. This is not proof that the photo is genuine or the water is safe.</p>{review?.confirmed?<div role="status" className="confirmed-state">✓ Your confirmation is saved.</div>:<><label className="attestation"><input type="checkbox" checked={attested} onChange={e=>setAttested(e.target.checked)}/>I personally saw the same condition here.</label><button className="confirm-button" onClick={confirmObservation} disabled={!attested||!review||reviewLoading||reviewSaving}>{reviewSaving?'Saving confirmation…':'👀 I saw this too'}{review?' · '+review.count:''}</button></>}<small>One per browser identity. Not unique-person verification.</small></section>{reviewError&&<div className="notice" role="alert">{reviewError}</div>}<button onClick={exportData}><Download/>Export evidence as JSON</button></section>}</dialog>
 <dialog ref={menuRef} className="menu-dialog" aria-label="Limnora navigation" onClick={e=>{if(e.target===e.currentTarget)menuRef.current?.close()}}>
 <div className="menu-sheet"><div className="menu-heading"><div><strong>Limnora</strong><p>Community freshwater observations</p></div><button aria-label="Close navigation menu" onClick={()=>menuRef.current?.close()}><X/></button></div>
 <nav aria-label="Menu pages"><Link href="/" onClick={()=>menuRef.current?.close()}><MapIcon/><span><strong>Explore</strong><small>Freshwater map & reports</small></span><ChevronRight/></Link>{[['about','About','What Limnora does',Info],['how-it-works','How to report','A practical field guide',BookOpen],['faq','FAQ','Answers & limitations',HelpCircle],['privacy','Privacy & data','What is public, what is stored',ShieldCheck]].map(([path,label,hint,Icon])=><Link href={'/'+path} key={path as string}><Icon/><span><strong>{label as string}</strong><small>{hint as string}</small></span><ChevronRight/></Link>)}</nav><div className="menu-bottom">Built for freshwater stewardship.<br/>Community evidence, not laboratory confirmation.</div></div></dialog>
 </main>
}
