import Link from 'next/link'
import { notFound } from 'next/navigation'

const pages:Record<string,{title:string;subtitle:string;sections:{title:string;text:string}[]}>= {
 about:{title:'About Limnora',subtitle:'A community record for urban freshwater ecosystems.',sections:[{title:'What we do',text:'Limnora helps people record visible changes in ponds, lakes and streams. Photographs, map points and observations create a record that communities can revisit.'},{title:'One Health',text:'Freshwater ecosystems connect environmental conditions, aquatic biodiversity and human well-being. Citizen observations can identify places needing professional follow-up; they are not laboratory measurements.'},{title:'Responsible AI',text:'AI screens visible evidence and explains uncertainty. Human observation remains central. The project is designed for AI-supported assessment, not automated declarations of water safety.'}]},
 'how-it-works':{title:'How to report',subtitle:'Choose water. Add evidence. Compare observations.',sections:[{title:'1. Select the water body',text:'Zoom into the map and click the water surface. Location permission is optional. Check the selected water-body name and coordinates before submitting.'},{title:'2. Share what you observed',text:'Choose a category, set the actual visit date, upload a genuine photo and describe visible coverage. Uploaded photos are re-encoded without GPS/EXIF metadata. Do not upload generated images as real field evidence. Stay on a safe public bank.'},{title:'3. Read the screening',text:'AI may offer visible evidence, alternatives and a follow-up suggestion. Suggest a correction or disagreement with your evidence; the original category stays unchanged. Add a new follow-up photo linked to the same water-body record. If AI is unavailable, your saved report remains available for human review.'},{title:'4. Add corroboration',text:'Use “I saw this too” only if you personally observed the same condition at the reported water body. Corroboration counts are community signals—not proof of identity, photo authenticity or safety.'}]},
 faq:{title:'Frequently asked questions',subtitle:'Clear expectations, before you submit.',sections:[{title:'Do I need an account or GPS?',text:'No. Browse and submit without signup. Location is optional and only helps center the map or show nearby reports. Report points are manually selected and are not GPS-verified.'},{title:'Can I confirm an observation?',text:'Yes, if you personally saw the same condition. One confirmation per report is allowed for each browser identity. Clearing cookies or using another browser can bypass this limit; it is not unique-person verification.'},{title:'Can AI tell whether water is safe?',text:'No. A photo cannot establish toxicity, pathogens, dissolved oxygen or potability. Never drink, touch or enter suspicious water based on a report or AI output.'},{title:'What if AI is unavailable?',text:'The observation stays saved. Open its detail view to retry screening. No result is fabricated when the provider fails.'},{title:'Why is a pond missing or unnamed?',text:'Map coverage and water-body names depend on OpenStreetMap and OpenFreeMap data. Small or unmapped water bodies may be absent. A selected unnamed water body can be given a local name, which is user-provided.'}]},
 privacy:{title:'Privacy & data use',subtitle:'Public evidence. No signup.',sections:[{title:'What is public',text:'Submitted photos, selected water-body coordinates, category, description, timestamps and AI assessment are public community evidence. Avoid faces, home addresses and private information. Upload only images you have permission to share.'},{title:'Location permission',text:'Browser location is optional. The app uses it to center the map and calculate nearby summaries. Submissions store your selected water point, not the browser GPS reading.'},{title:'AI and map providers',text:'Uploaded photos and descriptions are sent to an external AI provider through OpenRouter for screening. Map services receive ordinary tile requests, which reveal the viewed area and network information. These providers have their own privacy policies.'},{title:'Browser storage',text:'A first-party, HTTP-only cookie provides a random browser identity to limit duplicate confirmations. Only a hash is stored with confirmations and new observation/review attribution; these hashes are omitted from public API responses. Local storage remembers reports submitted from this browser. These are not identity or authenticity checks.'},{title:'Prototype limitations',text:'Limnora is a hackathon prototype, not an emergency service or certified monitoring system. Do not submit sensitive information. Public data exports contain the observation evidence and AI screening.'}]}
}
export function generateStaticParams(){return Object.keys(pages).map(info=>({info}))}
export default async function InfoPage({params}:{params:Promise<{info:string}>}){
 const {info}=await params,content=pages[info];if(!content)notFound()
 return <main><header className="app-header"><div className="header-inner"><Link href="/" className="brand"><span className="brand-mark"><img src="/limnora-mark.svg" width={56} height={56} alt=""/></span><span>Limnora<small>Freshwater. Evidence. Community.</small></span></Link><Link href="/" className="back-link">← Back to map</Link></div></header><article className="info-page"><p className="eyebrow">LIMNORA FIELD GUIDE</p><h1>{content.title}</h1><p className="info-lead">{content.subtitle}</p>{content.sections.map(s=><section key={s.title}><h2>{s.title}</h2><p>{s.text}</p></section>)}<nav aria-label="More information"><Link href="/about">About</Link><Link href="/how-it-works">How to report</Link><Link href="/faq">FAQ</Link><Link href="/privacy">Privacy</Link></nav><Link href="/" className="primary info-cta">Explore the map →</Link></article></main>
}
