'use client'
import {useState} from 'react'
import {observationEmojis} from '@/lib/observation-emojis'
import {WaterBodyEvidence} from '@/components/water-body-evidence'
import {RevisitComparison} from '@/components/revisit-comparison'
import {evidenceState,fieldLabels} from '@/lib/freshwater'
const labels:Record<string,string>={hyacinth:'Water hyacinth',algae:'Algae / scum',grass:'Aquatic plants',litter:'Litter',fish:'Dead fish',wildlife:'Aquatic life',flooding:'Flooding',unusual:'Unusual water',needs_review:'Uncertain — needs human review'}
export function EvidenceLoop({report,onChange,onFollowUp,timeline,onOpen}:{report:any;onChange:(r:any)=>void;onFollowUp:()=>void;timeline:any[];onOpen:(r:any)=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[type,setType]=useState('correction'),[note,setNote]=useState(''),[category,setCategory]=useState(report.category)
 const ai=report.ai_assessment||{}
 async function screen(){setBusy(true);setError('');try{const r=await fetch('/api/assess-observation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({observationId:report.id}),signal:AbortSignal.timeout(90000)});const d=await r.json();if(!r.ok)throw Error(d.error||'Screening failed');onChange({...report,ai_assessment:d});if(d.last_error)setError(d.last_error.message)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function review(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({observationId:report.id,type,note,category})});const d=await r.json();if(!r.ok)throw Error(d.error);onChange({...report,...d.observation});setNote('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <>
 <section className="assessment evidence-loop"><p className="eyebrow">EVIDENCE LOOP · HUMAN JUDGMENT FIRST</p><h3>AI evidence screening</h3>
 <strong>{ai.unavailable?'Screening unavailable':ai.status==='completed'?labels[ai.predicted_category]||ai.predicted_category:'Not assessed yet'}</strong>
 <p className="small-tag">{evidenceState(report)}</p>
 {ai.status==='completed'&&ai.last_error&&<p role="status">Showing the last completed screening. The latest retry failed.</p>}
 {ai.status==='completed'&&<><div className="evidence-verdict">{ai.image_relevant===false?'This image may not show freshwater field evidence.':ai.observation_supported?'The image supports the observer’s category.':'The image does not clearly support the observer’s category.'}<br/><small>Model uncertainty: {ai.uncertainty}. Not a calibrated probability.</small></div><h4>Visible evidence</h4>{ai.evidence?.map((s:string)=><p key={s}>{s}</p>)}{ai.alternatives?.length>0&&<><h4>Other explanations</h4>{ai.alternatives.map((s:string)=><p key={s}>{s}</p>)}</>}{ai.follow_up&&<div className="follow-up-question"><strong>Next useful observation</strong><p>{ai.follow_up}</p></div>}{ai.possible_impacts?.length>0&&<><h4>Potential One Health relevance</h4>{ai.possible_impacts.map((s:string)=><p key={s}>{s}</p>)}<small>Possible consequences, not measured findings.</small></>}<p className="small">Model: {ai.model} · {ai.prompt_version}<br/>Assessed {new Date(ai.assessed_at).toLocaleString()}</p></>}
 <small className="assessment-disclaimer">Screening only. Not laboratory confirmation or photo-authenticity verification.</small>
 {ai.last_error&&<p role="status">{ai.last_error.message}</p>}
 {ai.guidance_source&&<p className="small">One Health context is Limnora field guidance, not model-generated diagnosis. <a href={ai.guidance_source} target="_blank" rel="noreferrer">Mission reference ↗</a></p>}
 {report.field_context&&<dl className="field-notes">{Object.entries(report.field_context).map(([key,value])=><div key={key}><dt>{fieldLabels[key as keyof typeof fieldLabels]||key}</dt><dd>{String(value)}</dd></div>)}</dl>}
 <button onClick={screen} disabled={busy}>{busy?'Working…':ai.status==='completed'?'Reassess evidence':'Run AI screening'}</button></section>
 <section className="community-review"><h3>Your interpretation matters</h3><p>Suggest a correction, explain a disagreement, or add field context. The original observation stays unchanged; reviews remain attributed suggestions.</p>
 <form onSubmit={review}><label>Review type<select value={type} onChange={e=>setType(e.target.value)}><option value="correction">Suggest category correction</option><option value="disagreement">Different interpretation</option><option value="follow_up">Additional field context</option></select></label>{type==='correction'&&<label>Suggested category<select value={category} onChange={e=>setCategory(e.target.value)}>{Object.entries(labels).filter(([id])=>id!=='needs_review').map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>}<label>What evidence supports your review?<textarea required minLength={10} maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Describe what you actually saw, or explain why another interpretation fits."/></label><button disabled={busy||note.trim().length<10} type="submit">Save human review</button></form>
 <button className="follow-up-button" onClick={onFollowUp}>📷 Add a follow-up photo / revisit</button></section>
 {error&&<div role="alert" className="notice">{error}</div>}
 <section className="evidence-history"><h3>Traceable review history</h3><p className="small">Original observer category: {labels[report.category]||report.category}. Suggestions do not silently change it.</p>{!(ai.review_history?.length||ai.assessment_history?.length)&&<p>No review events yet.</p>}{ai.assessment_history?.map((event:any,index:number)=><article key={'ai'+index}><strong>AI interpretation: {labels[event.predicted_category]||event.predicted_category}</strong><small>{new Date(event.assessed_at).toLocaleString()} · {event.model}</small><p>{event.observation_supported?'Supported observer category':'Questioned observer category'} · uncertainty {event.uncertainty}</p></article>)}{ai.review_history?.map((event:any)=><article key={event.id}><strong>{event.type==='correction'?'Suggested correction: '+labels[event.proposed_category]:event.type==='disagreement'?'Different interpretation':'Additional context'}</strong><small>{new Date(event.created_at).toLocaleString()} · {event.role==='original_observer'?'Original browser observer':'Community reviewer'}</small><p>{event.note}</p></article>)}</section>
 <section className="evidence-history"><h3>Water-body evidence timeline</h3><p className="small">{report.water_body_id?'Linked by the saved community water-body ID.':'Legacy record without a linked water-body identity. Add a revisit to start its record.'} Counts are observations, not water-quality measurements.</p>{timeline.length?timeline.map(r=><button className="timeline-row" key={r.id} onClick={()=>onOpen(r)}><span>{observationEmojis[r.category]}</span><span><strong>{labels[r.category]}</strong><small>Observed {new Date(r.observed_at||r.created_at).toLocaleString()}{r.ai_assessment?.parent_id?' · follow-up':''}</small></span></button>):<p>This is the first linked observation.</p>}</section>
 <RevisitComparison report={report} timeline={timeline} onRevisit={onFollowUp}/>
 <WaterBodyEvidence body={report.water_body} reports={timeline} onOpen={onOpen} onRevisit={onFollowUp}/>
 </>
}
