'use client'
import {useState} from 'react'
import {fieldLabels,revisitTask,compareVisits,evidenceState} from '@/lib/freshwater'
export function RevisitComparison({report,timeline,onRevisit}:{report:any;timeline:any[];onRevisit:()=>void}){
 const task=revisitTask(report),children=timeline.filter(r=>r.ai_assessment?.parent_id===report.id)
 const parent=timeline.find(r=>r.id===report.ai_assessment?.parent_id)
 const base=parent||report,candidates=parent?[report]:children
 const [selected,setSelected]=useState('')
 const next=candidates.find(r=>r.id===selected)||candidates[0]
 const comparison=next?compareVisits(base,next):null
 return <section className="panel revisit-plan"><p className="eyebrow">OBSERVATION → QUESTION → REVISIT</p><h3>Next useful observation</h3><span className="small-tag">{task.reason}</span><p>{task.question}</p><ul>{task.checklist.map(item=><li key={item}>{item}</li>)}</ul><button onClick={onRevisit}>📷 Record a linked revisit</button><h3>What did the second visit add?</h3><p className="small">Linked visits are observer submissions, not verified photographs. Different views, lighting and seasons limit comparison. No automated recovery or water-health score is inferred.</p>{!next?<p>Revisit pending — this is a next-data request, not completed field work.</p>:<>{candidates.length>1&&<label>Choose linked visit<select value={next.id} onChange={e=>setSelected(e.target.value)}>{candidates.map(r=><option key={r.id} value={r.id}>{new Date(r.observed_at||r.created_at).toLocaleString()}</option>)}</select></label>}<div className="one-health-note"><h4>What the second visit added</h4><p>{comparison!.added.length?'Previously unknown context added: '+comparison!.added.join(', '):'No previously unknown structured context added.'}</p><p>{comparison!.changed.length?'Observer-reported differences: '+comparison!.changed.join(', '):'No known field values differ.'}</p><p>Original: {comparison!.beforeState}<br/>Revisit: {comparison!.afterState}</p>{comparison!.interpretationChanged&&<p>AI interpretations differ between visits. Compare framing and visible evidence.</p>}<h4>Still unresolved</h4><p>Photo authenticity, comparable framing and laboratory conditions remain unverified.</p><small>A changed observation does not establish ecological improvement or deterioration.</small></div><div className="revisit-pair">{[base,next].map((r,i)=><article key={r.id}><h4>{i?'Linked revisit':'Original observation'}</h4><img src={r.photo_url} alt={i?'Submitted revisit photograph':'Submitted original photograph'}/><p>{new Date(r.observed_at||r.created_at).toLocaleString()}</p><p>Observer category: {r.category}</p><p>Observer-estimated cover: {r.coverage_level||'Unknown'}</p><dl className="field-notes">{Object.entries(fieldLabels).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{r.field_context?.[key]||'Unknown'}</dd></div>)}</dl><p>AI interpretation: {r.ai_assessment?.status==='completed'?r.ai_assessment.predicted_category:'Not screened'}</p><p>{r.description}</p></article>)}</div></>}</section>
}
