'use client'
import {reviewerQueue,evidenceState,researcherBrief} from '@/lib/freshwater'
export function ReviewerWorkbench({reports,onOpen,onRevisit}:{reports:any[];onOpen:(r:any)=>void;onRevisit:(r:any)=>void}){
 const queue=reviewerQueue(reports)
 function download(report:any){const linked=reports.filter(r=>r.water_body_id===report.water_body_id&&report.water_body_id||r.id===report.id);const url=URL.createObjectURL(new Blob([researcherBrief(report.water_body,linked)],{type:'text/markdown'}));const a=document.createElement('a');a.href=url;a.download='limnora-researcher-brief.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className="review-workbench" id="review-workbench" aria-labelledby="review-title"><p className="eyebrow">REVIEWER WORKBENCH</p><h2 id="review-title">Evidence needing human attention</h2><p>Priorities describe reported concerns and missing evidence. They are not measured environmental danger rankings. Summaries cover loaded records only.</p>
 {!queue.length&&<div className="panel"><h3>No evidence loaded</h3><p>Add an original freshwater observation, load more records, or change the filters.</p></div>}
 <div className="review-grid">{queue.slice(0,24).map(item=><article className="panel reviewer-card" key={item.report.id}><div className="review-card-header"><img src={item.report.photo_url} alt="Submitted freshwater evidence" loading="lazy"/><div><p className="eyebrow">{item.priority}</p><h3>{item.report.water_body?.name||'Unnamed water body'}</h3><time>{new Date(item.report.observed_at||item.report.created_at).toLocaleString()}</time></div></div><div className="evidence-badges"><span>Evidence: {evidenceState(item.report)}</span><span>Visit: {item.report.ai_assessment?.parent_id?'Linked revisit':'Original observation'}</span></div><dl className="field-notes"><div><dt>Observer</dt><dd>{item.report.category}</dd></div><div><dt>Independent AI</dt><dd>{item.report.ai_assessment?.status==='completed'?item.report.ai_assessment.predicted_category:'Pending / unavailable'}</dd></div></dl><ul>{item.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul><div className="researcher-handoff"><h4>Reviewer → researcher handoff</h4><p><strong>Next field question:</strong> {item.nextQuestion}</p><small>{item.revisits} linked revisits in this view. Source evidence and original labels remain traceable.</small><div className="export-actions"><button onClick={()=>onOpen(item.report)}>Inspect / add review</button><button onClick={()=>onRevisit(item.report)}>Plan revisit</button><button onClick={()=>download(item.report)}>Download brief</button></div></div></article>)}</div>{queue.length>24&&<p>Showing the first 24 review cards. Refine the category or time filter for other records.</p>}</section>
}
