'use client'
import {bodySummary,evidenceState,fieldLabels,guidance,evidenceBrief,fhirPrototypeBundle,reviewerQueue,researcherBrief} from '@/lib/freshwater'
export function WaterBodyEvidence({body,reports,onOpen,onRevisit}:{body:any;reports:any[];onOpen:(r:any)=>void;onRevisit:(r:any)=>void}){
 const summary=bodySummary(reports),last=summary.last,guide=guidance[last?.category]||guidance.unusual
 const queue=reviewerQueue(reports)
 function downloadBrief(){const url=URL.createObjectURL(new Blob([researcherBrief(body,reports)],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='limnora-researcher-brief.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function downloadJson(){const url=URL.createObjectURL(new Blob([JSON.stringify(evidenceBrief(body,reports),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='limnora-water-body-evidence.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function downloadFhir(){const url=URL.createObjectURL(new Blob([JSON.stringify(fhirPrototypeBundle(body,reports),null,2)],{type:'application/fhir+json'}));const a=document.createElement('a');a.href=url;a.download='limnora-fhir-prototype-bundle.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className="panel body-evidence"><p className="eyebrow">FRESHWATER EVIDENCE RECORD</p><h2>{body?.name||last?.description?.split(':')[0]||'Selected water body'}</h2>
 <p className="provenance-line">{body?.type||'Unknown kind'} · {body?.source_metadata?.source==='osm'?'OSM geometry matched':'Community / legacy water point'} · {body?.source_metadata?.freshwater_status==='observer_declared'?'Freshwater declared by observer':'Freshwater provenance unknown'}</p>
 {body?.source_metadata?.source_url&&<a href={body.source_metadata.source_url} target="_blank" rel="noreferrer">View mapped feature ↗</a>}
 <div className="body-metrics"><div><strong>{reports.length}</strong><small>observations in view</small></div><div><strong>{summary.screened}</strong><small>AI screened</small></div><div><strong>{summary.disputed}</strong><small>disputed</small></div></div>
 {last?<><p>Last observed <strong>{new Date(last.observed_at||last.created_at).toLocaleString()}</strong></p><div className="one-health-note"><h3>Observed</h3><p>{last.description||'Photo observation recorded.'}</p><h3>Why document this?</h3><p>{guide.meaning}</p><small>General reference for reviewer context: <a href={guide.source} target="_blank" rel="noreferrer">source guidance</a>. Not a diagnosis of this water body.</small><h3>Who can use this record?</h3><p>A community observer can add a comparable bank photograph. A local freshwater researcher or environmental officer can review the source evidence and decide whether field sampling is needed.</p><h3>Next useful evidence</h3><p>{last.ai_assessment?.follow_up||guide.next}</p><button onClick={()=>onRevisit(last)}>📷 Plan a revisit / add photo</button></div></>:<p>No observations yet. Start this body's evidence record.</p>}
 <h3>Uncertain / needs follow-up</h3><p className="small">Reasons reflect missing or conflicting evidence, not water-quality scores.</p>{summary.reasons.length?summary.reasons.slice(0,6).map(({report,reason})=><button className="follow-up-row" key={report.id} onClick={()=>onOpen(report)}><strong>{reason}</strong><small>{new Date(report.observed_at||report.created_at).toLocaleDateString()} · Open supporting evidence</small></button>):<p>No missing-evidence reasons in this view. This does not establish healthy water.</p>}
 <h3>Reviewer workbench</h3><p className="small">Priorities reflect reported concerns and evidence gaps. They do not rank measured environmental danger.</p>{queue.slice(0,8).map(item=><article className="one-health-note" key={item.report.id}><strong>{item.priority}</strong><p>{item.report.category} · {evidenceState(item.report)}{item.report.ai_assessment?.parent_id?' · Linked revisit':''}</p><ul>{item.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul><p><strong>Next question:</strong> {item.nextQuestion}</p><p>{item.revisits} linked revisits in view</p><div className="export-actions"><button onClick={()=>onOpen(item.report)}>Inspect source evidence</button><button onClick={()=>onRevisit(item.report)}>Collect follow-up evidence</button></div></article>)}
 <div className="export-actions"><button onClick={downloadBrief} disabled={!reports.length}>Download researcher brief</button><button onClick={downloadJson} disabled={!reports.length}>Export Limnora JSON</button><button onClick={downloadFhir} disabled={!reports.length}>Export FHIR prototype</button></div><p className="small">Includes loaded source observations, field notes, AI provenance and next questions. FHIR export is a prototype handoff, not profile-validated or official OneAquaHealth integration.</p>
 <h3>Observation timeline</h3>{summary.ordered.map(r=><button className="follow-up-row" key={r.id} onClick={()=>onOpen(r)}><strong>{r.category} · {evidenceState(r)}</strong><small>{new Date(r.observed_at||r.created_at).toLocaleString()}</small></button>)}
 {last?.field_context&&<><h3>Latest observer field notes</h3><dl className="field-notes">{Object.entries(last.field_context).map(([key,value])=><div key={key}><dt>{fieldLabels[key as keyof typeof fieldLabels]||key}</dt><dd>{String(value)}</dd></div>)}</dl></>}
 </section>
}
